spring:
#  security:
#    user:
#      name: admin
#      password: 1234

  datasource:
      url: jdbc:mysql://localhost:3306/education
      username: root
      password:

#  datasource:
#    url: jdbc:mysql://containers-us-west-26.railway.app:6534/railway
#    username: root
#    password: QsdNQ4A7Cv4GQfC7GEgP

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

   